In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [4]:
std=pd.read_csv(r"C:\Users\hp\Data Analyst\csv\Student_Performance.csv")

In [5]:
std

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
ob=std.select_dtypes(["object"])

In [8]:
ob

Extracurricular Activities
0                           Yes
1                            No
2                           Yes
3                           Yes
4                            No
...                         ...
9995                        Yes
9996                        Yes
9997                        Yes
9998                        Yes
9999                         No

[10000 rows x 1 columns]

In [9]:
le=LabelEncoder()

In [10]:
le

LabelEncoder()

In [11]:
ob["ECA"]=le.fit_transform(ob)

In [12]:
ob

Extracurricular Activities  ECA
0                           Yes    1
1                            No    0
2                           Yes    1
3                           Yes    1
4                            No    0
...                         ...  ...
9995                        Yes    1
9996                        Yes    1
9997                        Yes    1
9998                        Yes    1
9999                         No    0

[10000 rows x 2 columns]

In [13]:
con=pd.concat(objs=[std,ob],axis=1)

In [14]:
con

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  \
0                                    1               91.0   
1                                    2               65.0   
2                                    2               45.0   
3                                    2               36.0   
4                                    5               66.0   
...                                ...                ...   
9995                                 2               23.0   
9996                                 5               58.0   
9997                                 5               74.0   
9998                                 0               95.0   
9999                                 1               64.0   

     Extracurricular Activities  ECA  
0                           Yes    1  
1                            No    0  
2                           Yes    1  
3                           Yes    1  
4                            No    0  
...                         ...  ...  
9995                        Yes    1  
9996                        Yes    1  
9997                        Yes    1  
9998                        Yes    1  
9999                         No    0  

[10000 rows x 8 columns]

In [15]:
con.drop(["Extracurricular Activities"],axis=1,inplace=True)

In [16]:
con

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  Performance Index  ECA  
0                                    1               91.0    1  
1                                    2               65.0    0  
2                                    2               45.0    1  
3                                    2               36.0    1  
4                                    5               66.0    0  
...                                ...                ...  ...  
9995                                 2               23.0    1  
9996                                 5               58.0    1  
9997                                 5               74.0    1  
9998                                 0               95.0    1  
9999                                 1               64.0    0  

[10000 rows x 6 columns]

In [17]:
y=con["Performance Index"]

In [18]:
pd.DataFrame(y)

Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

In [19]:
X=con.drop(['Performance Index'],axis=1)

In [20]:
X

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  ECA  
0                                    1    1  
1                                    2    0  
2                                    2    1  
3                                    2    1  
4                                    5    0  
...                                ...  ...  
9995                                 2    1  
9996                                 5    1  
9997                                 5    1  
9998                                 0    1  
9999                                 1    0  

[10000 rows x 5 columns]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scalar=StandardScaler()

In [23]:
scalar

StandardScaler()

In [24]:
Xscaled=scalar.fit_transform(X)

In [25]:
Xscaled

array([[ 0.77518771,  1.70417565,  1.45620461, -1.24975394,  1.01045465],
       [-0.38348058,  0.72391268, -1.49229423, -0.90098215, -0.98965352],
       [ 1.16141048, -1.06362569,  0.27680507, -0.90098215,  1.01045465],
       ...,
       [ 0.38896495,  0.7815752 ,  0.86650484,  0.1453332 ,  1.01045465],
       [ 1.54763324,  1.5888506 ,  0.27680507, -1.59852572,  1.01045465],
       [ 0.77518771,  0.26261245,  0.86650484, -1.24975394, -0.98965352]])

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
Xtrain,Xtest,ytrain,ytest=train_test_split(Xscaled,y,test_size=.2,random_state=7)

In [28]:
std.size

60000

In [29]:
std.shape

(10000, 6)

In [30]:
Xtrain.shape

(8000, 5)

In [31]:
Xtest.shape

(2000, 5)

In [32]:
ytrain.shape

(8000,)

In [33]:
ytest.shape

(2000,)

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
model=LinearRegression()

In [36]:
model

LinearRegression()

In [37]:
model.fit(Xtrain,ytrain)

LinearRegression()

In [38]:
model.coef_

array([ 7.38638279, 17.65478746,  0.82215591,  0.53904199,  0.31398283])

In [39]:
model.intercept_

55.235558921258

In [40]:
predictn=model.predict(Xtest)

In [41]:
predictn

array([61.37619419, 76.50257715, 71.58795192, ..., 33.76832339,
       53.91654484, 51.0777606 ])

In [42]:
residual=ytest-predictn

In [43]:
residual

1977    4.623806
3880    0.497423
52      3.412048
2551    0.530082
2246   -1.398976
          ...   
9505   -1.204456
2836    0.127641
1169    2.231677
9929    2.083455
8486   -0.077761
Name: Performance Index, Length: 2000, dtype: float64

In [44]:
import joblib

In [45]:
joblib.dump(model,"LinearRegression.pkl")

['LinearRegression.pkl']

In [46]:
joblib.dump(le,"Encoder.pkl")

['Encoder.pkl']

In [47]:
joblib.dump(scalar,"Scaler.pkl")

['Scaler.pkl']

In [48]:
Xtrain

array([[ 0.38896495,  1.5888506 ,  0.27680507,  1.54042034, -0.98965352],
       [ 0.77518771,  0.26261245,  0.86650484,  1.54042034, -0.98965352],
       [-1.54214888,  1.01222532,  0.27680507, -1.59852572,  1.01045465],
       ...,
       [ 1.54763324,  1.35820049,  1.45620461,  0.49410499,  1.01045465],
       [-0.76970335, -0.37167536,  1.45620461,  1.19164856,  1.01045465],
       [ 1.16141048,  0.32027498, -1.49229423, -1.24975394, -0.98965352]])

In [96]:
X

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  ECA  
0                                    1    1  
1                                    2    0  
2                                    2    1  
3                                    2    1  
4                                    5    0  
...                                ...  ...  
9995                                 2    1  
9996                                 5    1  
9997                                 5    1  
9998                                 0    1  
9999                                 1    0  

[10000 rows x 5 columns]